public with sharing class opportunityTCVUpdate{
    public static void TCVvalueUpdate(List<Opportunity> Oppty)
    {    
       /* list<opportunitylineitem> oplinelist = new list<opportunitylineitem>();
                list<opportunity> oplist = new list<opportunity>();
        set<Id> setId =  new set<Id>();
        for(opportunity op : Oppty)
        {
            setid.add(op.id);
        }
          
          for(opportunity op : [select Id, amount, Total_Contract_Value__c,  Product_Count__c, child_records__c  from opportunity where Id In : SetId])
          {
              if (op.child_records__c  == FALSE)
              {
                  op.Total_Contract_Value__c= op.amount;
              }
              
              oplist.add(op);
          }
          
          if(oplist.size() > 0 && oplist!=NULL)
          {
          update oplist;
          }*/
        
    }  
}